### ISSUE TITLE
AMD loaders break other downstream dependents due to grunt compilation order requirement

### ISSUE THREAD

**Issue by mikeatlas** [shutterstock/rickshaw#525]
`src/helpers/endUMD.js` (via https://github.com/shutterstock/rickshaw/pull/403) confuses Rails asset pipeline when this library is imported via the `rails-assets` gem (connects Rails to Bower):

``` Ruby
# Gemfile
source "https://rails-assets.org/"
gem "rails-assets-rickshaw"
```

``` Ruby
# assets.rb 
Rails.application.config.assets.precompile += %w( *.js )
```

When running `RAILS_ENV=production rake assets:precompile` (in production), what happens is that Sprockets encounters the invalid partial JS file and then aborts. This is due to the fact that rails-assets pulls and compiles via Sprockets and _not_ bower/grunt scripts; [thus endUMD.js](https://github.com/fjorgemota/rickshaw/blob/a22bdfa173977039cdb2da9e9a3e59f539dc043a/Makefile#L54) merely looks like a bad JavaScript file:

```
/gems/rails-assets-rickshaw-1.5.1/app/assets/javascripts/rickshaw/src/helpers/endUMD.js
rake aborted!
TypeError: no implicit conversion of nil into String
/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:14:in `update'
/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:14:in `initialize'
/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
```

An ugly hack that got me around this is to allow nil to be implicitly cast to an empty string in order to squelch the complaining Sprockets steps:

``` Ruby
# config/initializers/nil_class.rb
class NilClass
  def to_str
    ''
  end
end
```

but this is really bad-behavior kind of thing to do to to your entire Ruby application. 

Is there any possible way you might consider a different way to "modularize" your library, such as adding a task in your compilation which injects the start/end UMD wrappers from non `.js` extension files as a post-processing step instead, perhaps?

**Comment by mikeatlas** [comment]
Essentially your `Makefile` needs to rename the startUMD.js.prepend and endUMD.js.apped files, then it could prepend and append the start/end clauses. Maybe I'll make a PR for this, but it's pretty low on my list.
