### ISSUE TITLE
rendering a dashed line

### ISSUE THREAD

**Issue by niemyjski** [shutterstock/rickshaw#532]
Is there a good way to render a dashed line (http://www.d3noob.org/2013/01/making-dashed-line-in-d3js.html)? If not, can this be added?

**Comment by funvit** [comment]
Write custom graph renderer (with some sort of hack):

```
Rickshaw.namespace('Rickshaw.Graph.Renderer.DottedLine');
Rickshaw.Graph.Renderer.DottedLine = Rickshaw.Class.create( Rickshaw.Graph.Renderer.Line, {
    name: 'dotted_line',
    _styleSeries: function(series) {
        var result = Rickshaw.Graph.Renderer.Line.prototype._styleSeries.call(this, series);
        d3.select(series.path).style("stroke-dasharray", '5, 2');
        return result;
    }
});
```
and then
```
new Rickshaw.Graph({
  ...
  renderer: Rickshaw.Graph.Renderer.DottedLine,
  ...
});
```

**Comment by niemyjski** [comment]
@funvit awesome :) Any chance we could do a pull request for this? I think this would be really useful.

**Comment by niemyjski** [comment]
@funvit I get the following error with the code above.

```
TypeError: Cannot read property 'defaults' of undefined
    at klass.<anonymous> (http://localhost:9001/bower_components/rickshaw/rickshaw.js:3571:47)
    at Array.forEach (native)
    at klass.Rickshaw.Graph.Renderer.Multi.Rickshaw.Class.create._groups (http://localhost:9001/bower_components/rickshaw/rickshaw.js:3556:16)
    at klass.Rickshaw.Graph.Renderer.Multi.Rickshaw.Class.create.domain (http://localhost:9001/bower_components/rickshaw/rickshaw.js:3521:21)
    at klass.domain (http://localhost:9001/bower_components/rickshaw/rickshaw.js:137:20)
    at discoverRange (http://localhost:9001/bower_components/rickshaw/rickshaw.js:495:30)
    at initialize (http://localhost:9001/bower_components/rickshaw/rickshaw.js:429:8)
    at new Rickshaw.Graph (http://localhost:9001/bower_components/rickshaw/rickshaw.js:707:7)
    at http://localhost:9001/components/rickshaw/rickshaw-directive.js:35:21
```
